version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests and save HTML report
          command: |
            . venv/bin/activate
            pytest --report=pytest-report.html --template=html1/index.html
            ls -la

      - store_artifacts:
          path: pytest-report.html
          destination: test-report

workflows:
  version: 2
  test-all:
    jobs:
      - test
