version: 2.1

jobs:
  python-job:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Set up venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run pytest with HTML1 report
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: pytest-report
          destination: pytest-report

workflows:
  build-and-test:
    jobs:
      - python-job
