version: 2.1

jobs:
  python-job:
    docker:
      - image: circleci/python:3.10.1-node-browsers
    steps:
      - checkout
      - run:
          name: Set up virtualenv
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests and generate HTML report
          command: |
            . venv/bin/activate
            pytest --reporter=html1 --report=report.html
      - store_artifacts:
          path: report.html
          destination: python-report

workflows:
  build-and-test:
    jobs:
      - python-job
