version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Set up virtualenv and install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests and generate basic HTML report
          command: |
            . venv/bin/activate
            pytest x_tests/task_test.py --html=report.html

      - store_artifacts:
          path: report.html
          destination: html-report

workflows:
  version: 2
  test_and_report:
    jobs:
      - test
